### ISSUE TITLE
Error: next3.4 could not get parsed

### ISSUE THREAD

**Issue by b0o** [aserowy/tmux.nvim#56] opened 2022-01-09 00:25 UTC
Starting in the latest commit (cb1f40177aa4c5580a75407c3ca2e72771e44c4a), I get the following error on startup:

```
Error detected while processing $XDG_CONFIG_HOME/nvim/init.lua:
next3.4 could not get parsed!
```

`next3.4` is my tmux version:

```
$ tmux -V
tmux next-3.4
```

I'm using `tmux-git` from the AUR.

Using the previous commit (6e9597afc6fc57d2338f785989251e1ba36ff39c) works without issue.

**Comment by twidxuga** [comment] 2022-01-09 01:15
This issue affects me as well. I am using tmux next-3.3.

**Comment by twidxuga** [comment] 2022-01-09 11:20
One possible fix, that works for me (and possibly for everyone else) is to change `lua/tmux/version/parse.lua` to:

```lua
local log = require("tmux.log")

local function get_order(char)
    if char == nil or char == "" then
        return 0
    end
    return string.byte(char) - string.byte("a") + 1
end

local M = {}
function M.from(value)
    if value == nil then
        log.error("nil could not get parsed!")
        return {}
    end

    if value:match("^[next]*-?%d+%.%d+[oa-z]?$") == nil then
        log.error(value .. " could not get parsed!")
        return {}
    end

    local index_dot = value:find("%.")
    local rel_index_patch = value:sub(index_dot):find("[a-z]")

    local minor
    if rel_index_patch == nil then
        minor = tonumber(value:sub(index_dot + 1))
    else
        minor = tonumber(value:sub(index_dot + 1, index_dot + rel_index_patch - 1))
    end

    local patch = 0
    if rel_index_patch ~= nil then
        patch = get_order(value:sub(index_dot + rel_index_patch))
    end

    local major = tonumber(value:sub(value:find("%d"), index_dot - 1))

    return {
        major = major,
        minor = minor,
        patch = patch,
    }
end

return M
```

**Comment by aserowy** [comment] 2022-01-09 13:20
Heho,

currently on small vacation with the family. I'll soon get home and look into the issue and the pr asap.

Kind regards
Alexander

**Comment by b0o** [comment] 2022-01-09 13:38
Thank you Alexander, no hurry on my end. Please enjoy your vacation with your family!

**Comment by aserowy** [comment] 2022-01-09 16:12
Heho,

can you please try the fix?

Kind regards

**Comment by aserowy** [comment] 2022-01-09 16:20
@twidxuga 
i made it a little bit more strict:

    value = value:gsub("next%-", "")

all specs added for the next- release :D

**Comment by twidxuga** [comment] 2022-01-09 16:56
Perfect, thank you!

**Comment by aserowy** [comment] 2022-01-09 17:13
Cool, ty for using my work! means much to me!
Closing the issue.

**Comment by twidxuga** [comment] 2022-01-09 17:14
Actually, I was just testing this. Tt doesn't work with:

`value = value:gsub("next%-", "")`

Because the '-' is not in the `value` argument to `function M.from(value)`

Suggest just removing the '%-' from the expression. So this should work:

`value = value:gsub("next", "")`

Thanks again!

**Comment by aserowy** [comment] 2022-01-09 18:22
ok, i hope we got it now :D

**Comment by twidxuga** [comment] 2022-01-09 18:36
Just tested and confirmed it works. 

Cheers, much appreciated!

**Comment by aserowy** [comment] 2022-01-09 18:50
Nice, thanks for the support

**Closed** 2022-01-09 18:50 UTC
Labels: bug

**Comment by b0o** [comment] 2022-01-10 06:37
It's working for me too, thank you! :tada:
